#!/usr/bin/env sh
set -eu

compatibility_doc="docs/runbooks/compatibility-matrix.md"
stability_doc="docs/runbooks/stability-contract.md"
upgrade_doc="docs/runbooks/upgrade-rollback-policy.md"
dr_doc="docs/runbooks/disaster-recovery.md"
evidence_doc="docs/runbooks/release-evidence-checklist.md"
ga_template="docs/runbooks/ga-readiness-review-template.md"
support_doc="docs/runbooks/support-boundaries.md"
admin_hardening_doc="docs/runbooks/admin-plane-hardening.md"
security_hardening_doc="docs/runbooks/security-hardening.md"
secure_defaults_plan="plan/features/13_artifact_integrity_and_secure_defaults.md"
inventory_doc="artifacts/release-evidence-inventory.md"
sbom_doc="artifacts/sbom/README.md"
provenance_doc="artifacts/provenance/README.md"
perf_profiles_doc="artifacts/performance-envelope/supported-profiles.v1.json"
perf_evidence_readme="artifacts/performance-envelope/README.md"
perf_publish_script="scripts/publish-performance-evidence.sh"
perf_manifest_check_script="scripts/check-performance-soak-capacity-manifests.sh"

test -f "$compatibility_doc"
test -f "$stability_doc"
test -f "$upgrade_doc"
test -f "$dr_doc"
test -f "$evidence_doc"
test -f "$ga_template"
test -f "$support_doc"
test -f "$admin_hardening_doc"
test -f "$security_hardening_doc"
test -f "$secure_defaults_plan"
test -f "$inventory_doc"
test -f "$sbom_doc"
test -f "$provenance_doc"
test -f "$perf_profiles_doc"
test -f "$perf_evidence_readme"
test -f "$perf_publish_script"
test -f "$perf_manifest_check_script"

grep -q '^# Compatibility Matrix$' "$compatibility_doc"
grep -q '^## Skew Policy$' "$compatibility_doc"
grep -q 'Security Patch Process' "$compatibility_doc"
grep -q 'check-release-artifacts.sh' "$compatibility_doc"

grep -q '^# Stability Contract$' "$stability_doc"
grep -q '^## Stable Surfaces$' "$stability_doc"
grep -q '^## Experimental Surfaces$' "$stability_doc"
grep -q '^## Breaking-Change Process$' "$stability_doc"
grep -q 'RuntimeMetadata' "$stability_doc"

grep -q '^# Upgrade and Rollback Policy$' "$upgrade_doc"
grep -q '^## Upgrade Flow$' "$upgrade_doc"
grep -q '^## Rollback Flow$' "$upgrade_doc"
grep -q 'upgrade_rollback_smoke' "$upgrade_doc"
grep -q 'insecure_dev_mode' "$upgrade_doc"

grep -q '^# Disaster Recovery and Restore Validation$' "$dr_doc"
grep -q '^## Backup Flow$' "$dr_doc"
grep -q '^## Restore Flow$' "$dr_doc"
grep -q '^## Restore Validation Checklist$' "$dr_doc"
grep -q 'credential' "$dr_doc"
grep -q 'snapshot_restore_smoke' "$dr_doc"

grep -q '^# Release Evidence Checklist$' "$evidence_doc"
grep -q '^## Required Evidence$' "$evidence_doc"
grep -q '^## Release Candidate Sign-Off Checklist$' "$evidence_doc"
grep -q 'EVID-008' "$evidence_doc"
grep -q 'EVID-009' "$evidence_doc"
grep -q 'EVID-010' "$evidence_doc"
grep -q 'EVID-011' "$evidence_doc"
grep -q 'EVID-012' "$evidence_doc"

grep -q '^# Feature 13: Artifact Integrity And Secure Defaults$' "$secure_defaults_plan"
grep -q '^## Goal$' "$secure_defaults_plan"
grep -q '^## Deliverables$' "$secure_defaults_plan"

grep -q '^# GA Readiness Review Template$' "$ga_template"
grep -q '^## Evidence Inventory$' "$ga_template"
grep -q '^## GA Exit Criteria$' "$ga_template"
grep -q '^## Support-Boundary Review$' "$ga_template"
grep -q 'go_with_exceptions' "$ga_template"
grep -q 'EVID-008' "$ga_template"
grep -q 'EVID-009' "$ga_template"
grep -q 'EVID-010' "$ga_template"
grep -q 'EVID-011' "$ga_template"
grep -q 'EVID-012' "$ga_template"

grep -q '^# Support Boundaries$' "$support_doc"
grep -q '^## Supported Deployment Topologies$' "$support_doc"
grep -q '^## Unsupported Or Deferred Topologies$' "$support_doc"
grep -q '^## Protocol And Feature Boundaries$' "$support_doc"
grep -q '^## Failure-Mode Support Boundaries$' "$support_doc"
grep -q 'Active-Active Dataplane Fleet With Shared Control Plane' "$support_doc"
grep -q 'Multi-Node Cache Peer Fan-Out' "$support_doc"
grep -q 'Kubernetes Gateway Translation And Controller Packaging' "$support_doc"
grep -q 'security.insecure_dev_mode' "$support_doc"
grep -q 'current HTTP/3 support boundary' "$support_doc"
grep -q 'downstream HTTP/1 and HTTP/3 paths can target upstream clusters configured with `transport: http3`' "$support_doc"
grep -q 'not yet supported: admin HTTP/3 listeners' "$support_doc"
grep -q 'secure-default boundary expansion gate' "$support_doc"

grep -q '^# Admin Plane Hardening$' "$admin_hardening_doc"
grep -q '^## Supported Admin Auth Models$' "$admin_hardening_doc"
grep -q 'signed_headers' "$admin_hardening_doc"
grep -q 'nonce' "$admin_hardening_doc"
grep -q '<SECRET_ENV>_FILE' "$admin_hardening_doc"

grep -q '^# Security Hardening$' "$security_hardening_doc"
grep -q '^## Secure-Default Boundary Expansion Gate$' "$security_hardening_doc"
grep -q 'Before broadening support boundaries for discovery, auth, extension, or HTTP/3 surfaces' "$security_hardening_doc"
grep -q 'artifact attestation remains required in the default production posture' "$security_hardening_doc"
grep -q 'security.insecure_dev_mode' "$security_hardening_doc"
grep -q 'artifacts/sbom/README.md' "$security_hardening_doc"
grep -q 'artifacts/provenance/README.md' "$security_hardening_doc"

grep -q 'Extension hook and policy plugin contract' "$compatibility_doc"
grep -q 'extension `api_version = v1`' "$compatibility_doc"
grep -q 'Incompatible plugin API versions are rejected at registration' "$compatibility_doc"

grep -q '^# Release Evidence Inventory$' "$inventory_doc"
grep -q 'EVID-001' "$inventory_doc"
grep -q 'EVID-008' "$inventory_doc"
grep -q 'EVID-009' "$inventory_doc"
grep -q 'EVID-010' "$inventory_doc"
grep -q 'EVID-011' "$inventory_doc"
grep -q 'EVID-012' "$inventory_doc"
grep -q 'ga-readiness-review-template.md' "$inventory_doc"
grep -q 'stability-contract.md' "$inventory_doc"
grep -q 'publish-performance-evidence.sh' "$perf_evidence_readme"

for evid in EVID-001 EVID-002 EVID-003 EVID-004 EVID-005 EVID-006 EVID-007 EVID-008 EVID-009 EVID-010 EVID-011 EVID-012; do
	grep -q "$evid" "$evidence_doc"
	grep -q "$evid" "$ga_template"
	grep -q "$evid" "$inventory_doc"
done

./scripts/check-performance-profiles.sh
./scripts/check-performance-soak-capacity-manifests.sh