[package]
name = "lb-proto-http"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
httparse = "1.9"
tokio = { version = "1.37", features = ["io-util"] }

[dev-dependencies]
proptest = "1.5"

[lints]
workspace = true
